@startuml
autonumber

Actor Sales_Clerk as SC
activate SC

SC -> “UI” : request to show catalog
activate “UI”
SC <-- “UI” : show categories as options
deactivate “UI”

SC -> “UI” : choose a category
activate “UI”
SC <-- “UI” : show categories as options
deactivate “UI”


deactivate SC
@enduml