@startuml
skinparam classAttributeIconSize 0

QuestionerUI --> Calc
Calc --> EvalVisitor

class QuestionerUI{
 +doShow()
 +headLine()
}
class Calc{
+validateGrammar()
}
class EvalVisitor{
extends LabeledExprBaseVisitor
}
@enduml